import {
  Eye,
  EyeOff,
  User,
  LockKeyhole,
  XCircle,
  Database,
  Phone,
  BookUserIcon,
  KeyRound,
  HomeIcon,
  LineChartIcon,
  NewspaperIcon,
  BellIcon,
  BellDotIcon,
  CloudRainIcon,
  SunIcon,
  CloudSnowIcon,
  CloudSunRainIcon,
  MoonIcon,
  CloudHailIcon,
  CloudIcon,
  CircleUserIcon,
  BellRing,
  PlusCircleIcon,
  ArrowUpDownIcon,
  WarehouseIcon,
  CameraIcon
} from "lucide-react-native"

// export the icons by naming yourself
export const Icons = {
  visible: Eye,
  visibleOff: EyeOff,
  loginUser: User,
  loginLock: LockKeyhole,
  xCircle: XCircle,
  database: Database,
  phone: Phone,
  bookUser: BookUserIcon,
  keyRound: KeyRound,
  home: HomeIcon,
  dashboard: LineChartIcon,
  post: NewspaperIcon,
  notification: BellIcon,
  newNotification: BellDotIcon,
  cloudRainIcon: CloudRainIcon,
  sunIcon: SunIcon,
  cloudSnowIcon: CloudSnowIcon,
  cloudSunRainIcon: CloudSunRainIcon,
  moonIcon: MoonIcon,
  cloudHailIcon: CloudHailIcon,
  cloudIcon: CloudIcon,
  circleUser: CircleUserIcon,
  contentNotification: BellRing,
  profile: User,
  plusCircle: PlusCircleIcon,
  warehouseIcon: WarehouseIcon,
  internet: ArrowUpDownIcon,
  camera: CameraIcon,
}
